Update pr.yml

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -28,6 +28,20 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
+      # Runs a single command using the runners shell
+      - name: Run a one-line script
+        run: echo [${{ secrets.MY_SECRET }}] Hello, world!
+      
+      - name: Save PR number
+        run: |
+          mkdir -p ./pr
+          echo ${{ github.event.number }} > ./pr/NR
+          cat ./pr/NR
+      
+      - name: Shows PR number
+        run: |
+          cat ./pr/NR
+
       # Runs a set of commands using the runners shell
       - name: 'Req #1 : Run test'
         run: |
@@ -36,4 +50,42 @@ jobs:
           ./runtests.sh
           cat runtests.out
           echo Tests executed.      
+
+      #- name: 'Tests results - ERROR'
+      #  if: ${{ failure() }}
+      #  run: |
+      #    echo Tests ERROR !!
+      #    exit 1
           
+      #- name: 'Tests results - OK'
+      #  if: ${{ success() }}
+      #  run: |
+      #    echo Tests OK !!
+      #    exit 0
+        
+      #- name: 'ALWAYS'
+      #  if: always()
+      #  run: |
+      #    echo ALWAYS !!
+      #    exit 0
+          
+      - name: 'Req #2 : Comment on PR '
+        uses: actions/github-script@v3
+        with:
+          github-token: ${{ secrets.SCS_TOKEN }}
+          script: |
+            var fs = require('fs');
+            var issue_number = ${{ github.event.number }};
+            var mysec = String(fs.readFileSync('./runtests.out'));
+            console.log("hola perola");
+            console.log( ${{ github.event.number }} );
+            console.log( mysec );
+            var com = 'Test PR. Return msg from tests command: ' + mysec;
+            await github.issues.createComment({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: issue_number,
+              body: com
+            });
+        
+     
